### ISSUE TITLE
CURL has disappeared??

### ISSUE THREAD

**Issue by xbouillet** [SonarSource/sonar-scanner-cli-docker#108]
I use sonarsource/sonar-scanner-cli:latest with gitLabCi

I use Curl in my script

Since today, i have a error message : 

$ curl -k -u "$SONAR_TOKEN":"" $SONAR_HOST_URL/api/qualitygates/project_status?analysisId=$analysisId -o result.txt;
/bin/bash: line 160: curl: command not found

In the latest versions of sonarsource/sonar-scanner-cli:latest, now curl is not installed ?

**Comment by sseide** [comment]
with new image there is only the "wget" implementation of busybox - which is broken in regard to TLS handling and verification and not usable due to this.

Best thing would be that Sonarsource reintroduces curl into their image to not have lots of people build (and maintain!) their own images. And this is no "new" feature, it just recreates the old status quo...

Thanks

**Comment by tobias-trabelsi-sonarsource** [comment]
as a reaction of [this](https://gitlab.alpinelinux.org/alpine/aports/-/issues/10446) still open issue we will reintroduce curl to this image.
