### ISSUE TITLE
New tag for each sonarsource/sonar-scanner-cli update

### ISSUE THREAD

**Issue by candrews** [SonarSource/sonar-scanner-cli-docker#128]
Currently, when a new `sonarsource/sonar-scanner-cli` image is pushed, the `4`, `4.6`, and ` latest` tags are updated.

Could you please also push a more specific tag for the exact version? For example, the current `latest` has `SONAR_SCANNER_VERSION=4.6.2.2472` so I'd love to see a `4.6.2.2472` tag pushed for it.

The advantage of pushing specific, exact version tags is that it allows users to consistency use the same image. In other words, if I use `sonarsource/sonar-scanner-cli:latest` today that means one image, but tomorrow it may mean another. In contrast, `sonarsource/sonar-scanner-cli:4.6.2.2472` would always means the same image. A workaround is to use a digest (ex, `sonarsource/sonar-scanner-cli:latest@sha256:7b994de4c7c915a0c53d824ada7ba8a7e2b79743fd380203ee59a4d90ecbbefa`) but that doesn't tell the sonar version (without inspecting the image to see what the `SONAR_SCANNER_VERSION` arg is set to), making determine what has changed and evaluating it for suitability more difficult.

Exact version tags also have the advantage of allowing tools such as dependabot and renovate to monitor for updates and submit PRs to make the updates, allowing us to know when new versions of the image are available and do our own testing to ensure suitability.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @candrews ,

can you explain why the build number is valuable to you? We are using it internally but this does not have any value to a user as far as i can tell. We will not tag `4.6.2.2472` followed by `4.6.2.2473` for the next push to the docker hub as this build number represents the build of the sonar-scanner-cli application that is shipped with this docker image.

In order to reduce complexity we opted to version this image based on the application version that is embedded in the image. if you want to use something like dependabot or renovate to always stay up 2 date if we rebuild the image, the solution of referencing the image by hash is for now the only one possible. If you just want to be notified when a new version of the scanner cli application is released i am more than happy to also push to the specific `major.minor.tag` off the application.

This will be tracked with https://jira.sonarsource.com/browse/DOCKER-58

**Comment by candrews** [comment]
> If you just want to be notified when a new version of the scanner cli application is released i am more than happy to also push to the specific `major.minor.tag` off the application.

That sounds fantastic! `major.minor.tag` would be great, our goal is, as you said, to use renovate, and pushing such image tags would allow us to meet that goal.

Thank you!

**Comment by tobias-trabelsi-sonarsource** [comment]
okay then feel free to follow the linked jira ticket regarding the implementation :+1:
