### ISSUE TITLE
Permission error when runing as non-root user with self-signed certificates

### ISSUE THREAD

**Issue by emzet** [SonarSource/sonar-scanner-cli-docker#141]
There is a [guide](https://docs.sonarqube.org/latest/analysis/scan/sonarscanner) how to run container as a non-root user also with warning regarding file permisions.

But when running docker container as non-root user with custom self-signed certificates:

```
docker run \
  --rm \
  --user="$(id -u):$(id -g)"
  -v ${YOUR_CERTS_DIR}/cacerts:/tmp/cacerts \
  -v ${YOUR_REPO}:/usr/src \
  -e SONAR_HOST_URL="http://${SONARQUBE_URL}" \
  sonarsource/sonar-scanner-cli
```
there is an error thrown:
```
keytool error: java.io.FileNotFoundException: /usr/lib/jvm/default-jvm/jre/lib/security/cacerts (Permission denied)
```

I think it can be somehow related to [this](https://github.com/SonarSource/sonar-scanner-cli-docker/blob/master/4/bin/entrypoint.sh#L18).

**Comment by carminevassallo** [comment]
Dear @emzet,

Thanks for reporting also this issue! As I said in my previous comment, we are trying to centralize the management of all bug reports and feature requests related to Sonar products in our [forum](https://community.sonarsource.com/).

If you think this issue is still relevant, could you please post it there? In the meantime, I'm closing it.
