### ISSUE TITLE
Found CVE for sonarsource/sonar-scanner-cli:4

### ISSUE THREAD

**Issue by mcdanr3** [SonarSource/sonar-scanner-cli-docker#144]
Please ensure your issue adheres to the following guidelines: 
- [x] Please check the problem is not already reported
- [x] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs
   - Hello, we're using your latest version of sonarsource/sonar-scanner-cli:4 and noticed that it has a CVE (CVE-2021-43616). Would it be possible to bump the version of node you're using? I can provide more info if you need it.

**Comment by mrbusche** [comment]
Looks like this is resolved with https://github.com/SonarSource/sonar-scanner-cli-docker/commit/b20faa10e751d2248cfbc551d79e8340ea49683b what is the timeline for a tagged release?

**Comment by carminevassallo** [comment]
Hi @mcdanr3,

Thanks for reporting this issue! As you might have noticed in the `README.md`, we are trying to centralize the management of all bug reports and feature requests related to Sonar products in our [forum](https://community.sonarsource.com/).

If you think this issue is still relevant, could you please post it there? In the meantime, I'm closing it.
