### ISSUE TITLE
Docker images for arm64

### ISSUE THREAD

**Issue by r0b0** [SonarSource/sonar-scanner-cli-docker#151]
Please build and push docker image of sonarsource/sonar-scanner-cli for linux/arm64 platform

**Comment by bbombardella** [comment]
Hi there 👋

I tried to build an linux/arm64 image of the project, but there seems to be a problem with the `shellcheck` package 🤔

https://github.com/SonarSource/sonar-scanner-cli-docker/blob/d02a5a2036e4a4f8161555d3664fe3fa2ffb9698/4/Dockerfile#L24

The problem is that the image is built on top of an older version of alpine (3.15). Upgrading to alpine 3.17 solve the problem

https://github.com/SonarSource/sonar-scanner-cli-docker/blob/d02a5a2036e4a4f8161555d3664fe3fa2ffb9698/4/Dockerfile#L1

**Comment by ericfunktxgroup** [comment]
from what i can see your base image is now based on alpine:3.17 - shouldn't you technical be able now to use buildx github action and QEMU (https://github.com/docker/setup-buildx-action) to build a docker image that can be used on amd64 and arm64 platform?

**Comment by ArieLevs** [comment]
it does not work
I've successfully built an ARM based sonarqube cli image from `alpine:3.17`, I'm able to run it on arm servers (graviton cpu), but then experience exactly same issue as here https://community.sonarsource.com/t/sonar-scanner-cli-freezing-at-various-stages/60585

**Comment by banbone** [comment]
Hey, not sure if this is still relevant, but I was able to successfully build the image using arm64 architecture using the repo as it is in it's current state. For the most part, the analysis works well, but there are issues with some of the plugins. Admittedly I have a weird use-case but to replicate, run the following command from the root of the repo:
`docker buildx build 4 --build-arg "SONAR_SCANNER_VERSION=4.8.0.2856" -f 4/Dockerfile --platform linux/arm64 -t banbone/sonar-scanner-cli:4`
If you don't want to build it yourself, feel free to pull my image from dockerhub to test it out, but I don't know what I'm doing with it to test if I'm honest!
