### ISSUE TITLE
Is it possible to inject ssl certificate ?

### ISSUE THREAD

**Issue by ulyssejdv** [SonarSource/sonar-scanner-cli-docker#168]
hi,

Is it possible to add a certificate to our private sonar instance ?

Manualy we use something like this : ` -Djavax.net.ssl.trustStore=sonarint.jks -Djavax.net.ssl.trustStorePassword=<password>`

![image](https://user-images.githubusercontent.com/12152859/232456890-3a1a3e95-8b5a-4c5e-ba5b-15413b1afa84.png)

**Comment by jCOTINEAU** [comment]
Hello @ulyssejdv, thanks a lot for taking the time to participate in the community.

I am not sure what use case you are describing ? 

Is it exposing a SonarQube server behind a reverse proxy with a custom certificate ? 

Or are you looking for the documentation to add a new CA to the sonar-scanner so that it communicates with your private SQ ? 
In that case you can follow the documentation [here](https://docs.sonarqube.org/latest/analyzing-source-code/scanners/sonarscanner/). Under the `Advanced Docker configuration ` section you will find the documentation to work with custom certificates.

Please let me know if that answer your question.

**Comment by ulyssejdv** [comment]
Hi @jCOTINEAU thank you for your response :)

You right, we expose an SQ instance behind a reverse proxy with a custom certificate.

I have created an image base on the sonar-scanner-cli.

```Dockerfile
FROM sonarsource/sonar-scanner-cli:latest

COPY certs/ /tmp/cacerts

RUN update-ca-certificates 
```

Thank you for your support.

**Comment by ulyssejdv** [comment]
I close the issue or you close the issue ?
