### ISSUE TITLE
Security Layer vulnerability in ash.c:6030 is busybox before 1.35. 

### ISSUE THREAD

**Issue by tbongiovani** [SonarSource/sonar-scanner-cli-docker#199]
Necessary upgrade docker image alpine://3.17

**Comment by carminevassallo** [comment]
Dear @tbongiovani,

Thanks for reporting this issue! As you might have noticed in the `README.md`, we are trying to centralize the management of all bug reports and feature requests related to Sonar products in our [forum](https://community.sonarsource.com/).

If you think this issue is still relevant, could you please post it there? In the meantime, I'm closing it.
