### ISSUE TITLE
User does not have enough permissions in the workdir

### ISSUE THREAD

**Issue by hbowron** [SonarSource/sonar-scanner-cli-docker#44]
The work directory (WORKDIR /usr/src) is owned by root and the user (USER scanner-cli) cannot create files/directories there, leading to:
```
ERROR: Error during SonarScanner execution
java.lang.IllegalStateException: Unable to load component class org.sonar.scanner.scan.ProjectLock
Caused by: java.lang.IllegalStateException: Failed to create work directory
Caused by: java.nio.file.AccessDeniedException: /usr/src/.scannerwork
```

This issue arises in multi-stage builds for example.  Hack solution is:
```
USER root
RUN chown scanner-cli:scanner-cli /usr/src
USER scanner-cli
```

While the real solution would probably be to add `chown scanner-cli:scanner-cli /usr/src` into one of the RUN commands

**Comment by michal-duda-sonarsource** [comment]
You're supposed to mount your project directory or mount the volume that contains your project to the `/usr/src` directory in the container, otherwise you will run an analysis on empty directory. In current version of the image you also have to set appropriate permissions on the directory/volume yourself. 

But indeed it still makes sense to add `RUN chown scanner-cli:scanner-cli /usr/src` just to properly handle the scenario when `/usr/src` is not mounted. We will fix it in https://jira.sonarsource.com/browse/MMF-2003
